<a href="https://colab.research.google.com/github/samarthya04/AD_Lab/blob/main/2205498_Week_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

In [ ]:
path = '/content/drive/MyDrive/AD Lab Datasets/Iris.csv'
df = pd.read_csv(path)

In [ ]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [ ]:
df = df.drop(['Id'], axis=1)
df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
X = df.drop('Species', axis=1)
y = df['Species']

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
model = LogisticRegression(max_iter=200)

In [ ]:
metrics = []

for feature in X.columns:
    X_train_feat = X_train[[feature]]
    X_test_feat = X_test[[feature]]

    model.fit(X_train_feat, y_train)

    y_pred = model.predict(X_test_feat)

    r2 = r2_score(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    amse = np.mean(np.abs(y_test - y_pred))

    n = len(y_test)
    p = 1
    adj_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)

    metrics.append({
        'Feature': feature,
        'R2': r2,
        'Adjusted R2': adj_r2,
        'MSE': mse,
        'AMSE': amse
    })

In [ ]:
metrics_df = pd.DataFrame(metrics)

In [ ]:
metrics_df

         Feature        R2  Adjusted R2       MSE      AMSE
0  SepalLengthCm  0.761526     0.753009  0.166667  0.166667
1   SepalWidthCm -0.573927    -0.630139  1.100000  0.633333
2  PetalLengthCm  1.000000     1.000000  0.000000  0.000000
3   PetalWidthCm  1.000000     1.000000  0.000000  0.000000